import type { Metadata } from "next";
import "./globals.css";
import Provider from "./prodiver";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "Flash Ai",
  description: "Generated by Pawan Dasila",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ConvexClientProvider>
          <Provider>{children}</Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
